# Site settings
title: Samuel Katz
email: sammykatz@sbcglobal.net
url: https://samkatz.github.io
description: "This is the online portfolio of Samuel Katz"
skills: "Software Engineer - Game Developer"
meta_author: Katz Samuel
resume: Resume (3/23/19)
resumeurl: https://drive.google.com/open?id=1v4uJ7VGFUYK-5fDGpodE-YfXSO8pWNei

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2D6927
  primary-rgb: "45,105,39"
  secondary: 1A5114 #FD6E8A
  secondary-dark: 093404 #A2122F

# Footer settings
footer:
  copyright: Samuel Katz
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/sammy.katz.37
  - title: github
    url: http://github.com/SamKatz
  - title: linkedin
    url: https://www.linkedin.com/in/samuel-katz-62439a14b/
  - title: bitbucket
    url: https://bitbucket.org/SamKatz/

# Postal address (add as many lines as necessary)
address:
  - line: Richardson, Texas

# Credits content
credits: 'This website was created using a template licensed under the <a href="https://www.apache.org/licenses/LICENSE-2.0">Apache License 2.0</a> that can be found <a href="https://github.com/jeromelachaud/freelancer-theme">here</a>.'

# Build settings
markdown: kramdown
permalink: pretty
